/***************************************************************************//**
* ISOUART IP definitions
*
********************************************************************************
* \copyright
* (c) 2016-2026, Infineon Technologies AG or an affiliate of
* Infineon Technologies AG.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#ifndef _CYIP_ISOUART_H_
#define _CYIP_ISOUART_H_

#include "cyip_headers.h"

/*******************************************************************************
*                                   ISOUART
*******************************************************************************/

#define ISOUART_SECTION_SIZE                    0x00010000UL

/**
  * \brief iso-UART Block (ISOUART)
  */
typedef struct {
  __IOM uint32_t CTL;                           /*!< 0x00000000 General control register. */
   __IM uint32_t INTERFACE_STATUS;              /*!< 0x00000004 Current state of the interface */
  __IOM uint32_t MULTI_READ_CTL;                /*!< 0x00000008 Control interpretation of the multi-read configuration register */
   __IM uint32_t RESERVED[5];
  __IOM uint32_t MASTER_CFG;                    /*!< 0x00000020 Master configuration register */
  __IOM uint32_t MASTER_START;                  /*!< 0x00000024 Trigger a write to the interface */
   __IM uint32_t LOW_INTERFACE_READ;            /*!< 0x00000028 Most recent data read from LOW interface */
   __IM uint32_t HIGH_INTERFACE_READ;           /*!< 0x0000002C Most recent data read from HIGH interface */
  __IOM uint32_t WAKE_DELAY_CFG;                /*!< 0x00000030 Wake sequence configuration */
   __IM uint32_t RESERVED1[3];
  __IOM uint32_t IF_GEN_DIAG;                   /*!< 0x00000040 General Diagnosis */
   __IM uint32_t IF_MULTI_READ_CFG;             /*!< 0x00000044 Multi-read configuration register */
   __IM uint32_t IF_CONFIG;                     /*!< 0x00000048 Interface configuration register, containing the current Device
                                                                ID */
  __IOM uint32_t IF_WDOG_CNT;                   /*!< 0x0000004C Interface watchdog register */
   __IM uint32_t CLK_STATUS;                    /*!< 0x00000050 Interface clock status */
  __IOM uint32_t UVD_CTL;                       /*!< 0x00000054 Under Voltage Detection Control */
   __IM uint32_t RESERVED2[2];
  __IOM uint32_t INTR;                          /*!< 0x00000060 Interrupt request register */
  __IOM uint32_t INTR_SET;                      /*!< 0x00000064 Interrupt set register */
  __IOM uint32_t INTR_MASK;                     /*!< 0x00000068 Interrupt mask register */
   __IM uint32_t INTR_MASKED;                   /*!< 0x0000006C Interrupt masked register */
   __IM uint32_t INTR_REG_ACCESS_P;             /*!< 0x00000070 Primary Register specific access interrupt cause */
   __IM uint32_t INTR_REG_ACCESS_S;             /*!< 0x00000074 Secondary Register specific access interrupt cause */
   __IM uint32_t RESERVED3[2];
  __IOM uint32_t ECC_CTL;                       /*!< 0x00000080 ECC control */
  __IOM uint32_t ECC_ERR_INJ;                   /*!< 0x00000084 ECC error injection */
   __IM uint32_t ECC_STATUS;                    /*!< 0x00000088 ECC status */
   __IM uint32_t RESERVED4;
  __IOM uint32_t DFT_CTL;                       /*!< 0x00000090 DFT Control Register */
   __IM uint32_t DFT_STATUS;                    /*!< 0x00000094 DFT Status Register */
   __IM uint32_t RESERVED5[26];
  __IOM uint32_t TRIG_INT_STRUCT[32];           /*!< 0x00000100 Structure defining trigger and interrupt response to events */
   __IM uint32_t RESERVED6[32];
  __IOM uint32_t SRAM_DATA[64];                 /*!< 0x00000200 128 word x 16 bit SRAM representing data available to iso-UART
                                                                interface */
   __IM uint32_t RESERVED7[64];
  __IOM uint32_t SRAM_WITH_ATTR[128];           /*!< 0x00000400 128 word x 16 bit (only 9 usable bits) containing attributes */
   __IM uint32_t RESERVED8[15935];
  __IOM uint32_t PHY_REG_TM;                    /*!< 0x0000FEFC Test Mode Register */
  __IOM uint32_t TRIM_PHY_V_HS;                 /*!< 0x0000FF00 Internal Voltage Trim for HS PHY */
  __IOM uint32_t TRIM_PHY_V_LS;                 /*!< 0x0000FF04 Internal Voltage Trim for LS PHY */
  __IOM uint32_t TRIM_PHY_ITH_HS;               /*!< 0x0000FF08 Current Trim for HS PHY */
  __IOM uint32_t TRIM_PHY_ITH_LS;               /*!< 0x0000FF0C Current Trim for LS PHY */
} ISOUART_Type;                                 /*!< Size = 65296 (0xFF10) */


/* ISOUART.CTL */
#define ISOUART_CTL_BC_WRITE_TURN_TIME_CTL_Pos  0UL
#define ISOUART_CTL_BC_WRITE_TURN_TIME_CTL_Msk  0x1UL
#define ISOUART_CTL_OVS_Pos                     1UL
#define ISOUART_CTL_OVS_Msk                     0xEUL
#define ISOUART_CTL_IFL_L_CMOSRCV_EN_Pos        8UL
#define ISOUART_CTL_IFL_L_CMOSRCV_EN_Msk        0x100UL
#define ISOUART_CTL_IFL_H_CMOSRCV_EN_Pos        9UL
#define ISOUART_CTL_IFL_H_CMOSRCV_EN_Msk        0x200UL
#define ISOUART_CTL_IFH_L_CMOSRCV_EN_Pos        10UL
#define ISOUART_CTL_IFH_L_CMOSRCV_EN_Msk        0x400UL
#define ISOUART_CTL_IFH_H_CMOSRCV_EN_Pos        11UL
#define ISOUART_CTL_IFH_H_CMOSRCV_EN_Msk        0x800UL
#define ISOUART_CTL_IFL_L_AUX_EN_Pos            12UL
#define ISOUART_CTL_IFL_L_AUX_EN_Msk            0x1000UL
#define ISOUART_CTL_IFL_H_AUX_EN_Pos            13UL
#define ISOUART_CTL_IFL_H_AUX_EN_Msk            0x2000UL
#define ISOUART_CTL_IFH_L_AUX_EN_Pos            14UL
#define ISOUART_CTL_IFH_L_AUX_EN_Msk            0x4000UL
#define ISOUART_CTL_IFH_H_AUX_EN_Pos            15UL
#define ISOUART_CTL_IFH_H_AUX_EN_Msk            0x8000UL
#define ISOUART_CTL_TRIG0_EMM_Pos               20UL
#define ISOUART_CTL_TRIG0_EMM_Msk               0x100000UL
#define ISOUART_CTL_TRIG1_EMM_Pos               21UL
#define ISOUART_CTL_TRIG1_EMM_Msk               0x200000UL
#define ISOUART_CTL_TRIG2_EMM_Pos               22UL
#define ISOUART_CTL_TRIG2_EMM_Msk               0x400000UL
#define ISOUART_CTL_TRIG3_EMM_Pos               23UL
#define ISOUART_CTL_TRIG3_EMM_Msk               0x800000UL
#define ISOUART_CTL_EMERGENCY_Pos               24UL
#define ISOUART_CTL_EMERGENCY_Msk               0x1000000UL
#define ISOUART_CTL_RESET_INTERFACE_Pos         25UL
#define ISOUART_CTL_RESET_INTERFACE_Msk         0x2000000UL
#define ISOUART_CTL_CRC_POLY_Pos                28UL
#define ISOUART_CTL_CRC_POLY_Msk                0x10000000UL
#define ISOUART_CTL_BLOCK_ID_EN_Pos             29UL
#define ISOUART_CTL_BLOCK_ID_EN_Msk             0x20000000UL
#define ISOUART_CTL_REGULATOR_BYPASS_Pos        30UL
#define ISOUART_CTL_REGULATOR_BYPASS_Msk        0x40000000UL
#define ISOUART_CTL_ENABLED_Pos                 31UL
#define ISOUART_CTL_ENABLED_Msk                 0x80000000UL
/* ISOUART.INTERFACE_STATUS */
#define ISOUART_INTERFACE_STATUS_INTERFACE_STATE_Pos 0UL
#define ISOUART_INTERFACE_STATUS_INTERFACE_STATE_Msk 0xFUL
#define ISOUART_INTERFACE_STATUS_REQUEST_STATE_Pos 4UL
#define ISOUART_INTERFACE_STATUS_REQUEST_STATE_Msk 0x70UL
#define ISOUART_INTERFACE_STATUS_HOST_COMMAND_Pos 8UL
#define ISOUART_INTERFACE_STATUS_HOST_COMMAND_Msk 0x700UL
#define ISOUART_INTERFACE_STATUS_REPLY_STATE_Pos 12UL
#define ISOUART_INTERFACE_STATUS_REPLY_STATE_Msk 0x7000UL
#define ISOUART_INTERFACE_STATUS_DEVID_TRANSMITTING_Pos 16UL
#define ISOUART_INTERFACE_STATUS_DEVID_TRANSMITTING_Msk 0x7F0000UL
#define ISOUART_INTERFACE_STATUS_PACKET_NUMBER_Pos 24UL
#define ISOUART_INTERFACE_STATUS_PACKET_NUMBER_Msk 0x7F000000UL
/* ISOUART.MULTI_READ_CTL */
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BASE_A_Pos 0UL
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BASE_A_Msk 0x7FUL
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BASE_B_Pos 8UL
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BASE_B_Msk 0x7F00UL
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BC_EN_Pos 31UL
#define ISOUART_MULTI_READ_CTL_MULTI_READ_BC_EN_Msk 0x80000000UL
/* ISOUART.MASTER_CFG */
#define ISOUART_MASTER_CFG_LOW_INTERFACE_MODE_Pos 0UL
#define ISOUART_MASTER_CFG_LOW_INTERFACE_MODE_Msk 0x3UL
#define ISOUART_MASTER_CFG_HIGH_INTERFACE_MODE_Pos 2UL
#define ISOUART_MASTER_CFG_HIGH_INTERFACE_MODE_Msk 0xCUL
#define ISOUART_MASTER_CFG_TRIG0_WRITE_DONE_Pos 4UL
#define ISOUART_MASTER_CFG_TRIG0_WRITE_DONE_Msk 0x10UL
#define ISOUART_MASTER_CFG_TRIG1_LOW_SRAM_FULL_Pos 5UL
#define ISOUART_MASTER_CFG_TRIG1_LOW_SRAM_FULL_Msk 0x20UL
#define ISOUART_MASTER_CFG_TRIG2_HIGH_SRAM_FULL_Pos 6UL
#define ISOUART_MASTER_CFG_TRIG2_HIGH_SRAM_FULL_Msk 0x40UL
#define ISOUART_MASTER_CFG_INTERNAL_LOOPBACK_Pos 7UL
#define ISOUART_MASTER_CFG_INTERNAL_LOOPBACK_Msk 0x80UL
#define ISOUART_MASTER_CFG_TX_BLOCK_ID_Pos      8UL
#define ISOUART_MASTER_CFG_TX_BLOCK_ID_Msk      0x700UL
#define ISOUART_MASTER_CFG_MASTER_MODE_Pos      12UL
#define ISOUART_MASTER_CFG_MASTER_MODE_Msk      0x1000UL
#define ISOUART_MASTER_CFG_MASTER_BITRATE_Pos   13UL
#define ISOUART_MASTER_CFG_MASTER_BITRATE_Msk   0x2000UL
#define ISOUART_MASTER_CFG_RECEIVE_MODE_Pos     14UL
#define ISOUART_MASTER_CFG_RECEIVE_MODE_Msk     0xC000UL
#define ISOUART_MASTER_CFG_LOW_INTERFACE_SRAM_SIZE_Pos 16UL
#define ISOUART_MASTER_CFG_LOW_INTERFACE_SRAM_SIZE_Msk 0x7F0000UL
#define ISOUART_MASTER_CFG_RESET_LOW_INTERFACE_SRAM_PTR_Pos 23UL
#define ISOUART_MASTER_CFG_RESET_LOW_INTERFACE_SRAM_PTR_Msk 0x800000UL
#define ISOUART_MASTER_CFG_HIGH_INTERFACE_SRAM_SIZE_Pos 24UL
#define ISOUART_MASTER_CFG_HIGH_INTERFACE_SRAM_SIZE_Msk 0x7F000000UL
#define ISOUART_MASTER_CFG_RESET_HIGH_INTERFACE_SRAM_PTR_Pos 31UL
#define ISOUART_MASTER_CFG_RESET_HIGH_INTERFACE_SRAM_PTR_Msk 0x80000000UL
/* ISOUART.MASTER_START */
#define ISOUART_MASTER_START_WRITE_DATA_Pos     0UL
#define ISOUART_MASTER_START_WRITE_DATA_Msk     0xFFFFUL
#define ISOUART_MASTER_START_ADDRESS_Pos        16UL
#define ISOUART_MASTER_START_ADDRESS_Msk        0x7F0000UL
#define ISOUART_MASTER_START_DEVICE_ID_Pos      24UL
#define ISOUART_MASTER_START_DEVICE_ID_Msk      0x3F000000UL
#define ISOUART_MASTER_START_READ_WRITE_Pos     30UL
#define ISOUART_MASTER_START_READ_WRITE_Msk     0x40000000UL
#define ISOUART_MASTER_START_SEND_WAKE_SEQUENCE_Pos 31UL
#define ISOUART_MASTER_START_SEND_WAKE_SEQUENCE_Msk 0x80000000UL
/* ISOUART.LOW_INTERFACE_READ */
#define ISOUART_LOW_INTERFACE_READ_READ_LOW_DATA_Pos 0UL
#define ISOUART_LOW_INTERFACE_READ_READ_LOW_DATA_Msk 0xFFUL
/* ISOUART.HIGH_INTERFACE_READ */
#define ISOUART_HIGH_INTERFACE_READ_READ_HIGH_DATA_Pos 0UL
#define ISOUART_HIGH_INTERFACE_READ_READ_HIGH_DATA_Msk 0xFFUL
/* ISOUART.WAKE_DELAY_CFG */
#define ISOUART_WAKE_DELAY_CFG_WAKE_CMD_DELAY_Pos 0UL
#define ISOUART_WAKE_DELAY_CFG_WAKE_CMD_DELAY_Msk 0x3FFFUL
/* ISOUART.IF_GEN_DIAG */
#define ISOUART_IF_GEN_DIAG_GPIO_WAKEUP_Pos     0UL
#define ISOUART_IF_GEN_DIAG_GPIO_WAKEUP_Msk     0x1UL
#define ISOUART_IF_GEN_DIAG_MOT_MOB_N_Pos       1UL
#define ISOUART_IF_GEN_DIAG_MOT_MOB_N_Msk       0x2UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR2_Pos   2UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR2_Msk   0x4UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR3_Pos   3UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR3_Msk   0x8UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR4_Pos   4UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR4_Msk   0x10UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR5_Pos   5UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR5_Msk   0x20UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR6_Pos   6UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR6_Msk   0x40UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR7_Pos   7UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR7_Msk   0x80UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR_15_8_Pos 8UL
#define ISOUART_IF_GEN_DIAG_RESERVED_ERR_15_8_Msk 0xFF00UL
/* ISOUART.IF_MULTI_READ_CFG */
#define ISOUART_IF_MULTI_READ_CFG_MULTI_READ_CFG_Pos 0UL
#define ISOUART_IF_MULTI_READ_CFG_MULTI_READ_CFG_Msk 0xFFFFUL
/* ISOUART.IF_CONFIG */
#define ISOUART_IF_CONFIG_NODE_ID_Pos           0UL
#define ISOUART_IF_CONFIG_NODE_ID_Msk           0x3FUL
#define ISOUART_IF_CONFIG_BLOCK_ID_Pos          6UL
#define ISOUART_IF_CONFIG_BLOCK_ID_Msk          0x1C0UL
#define ISOUART_IF_CONFIG_FN_Pos                11UL
#define ISOUART_IF_CONFIG_FN_Msk                0x800UL
/* ISOUART.IF_WDOG_CNT */
#define ISOUART_IF_WDOG_CNT_WDOG_CNT_Pos        0UL
#define ISOUART_IF_WDOG_CNT_WDOG_CNT_Msk        0xFFFFUL
/* ISOUART.CLK_STATUS */
#define ISOUART_CLK_STATUS_BR_COUNTER_Pos       0UL
#define ISOUART_CLK_STATUS_BR_COUNTER_Msk       0xFFUL
/* ISOUART.UVD_CTL */
#define ISOUART_UVD_CTL_FILT_LIMIT_Pos          0UL
#define ISOUART_UVD_CTL_FILT_LIMIT_Msk          0xFFFFUL
#define ISOUART_UVD_CTL_ENABLE_Pos              31UL
#define ISOUART_UVD_CTL_ENABLE_Msk              0x80000000UL
/* ISOUART.INTR */
#define ISOUART_INTR_WAKE_HIGH_Pos              0UL
#define ISOUART_INTR_WAKE_HIGH_Msk              0x1UL
#define ISOUART_INTR_WAKE_LOW_Pos               1UL
#define ISOUART_INTR_WAKE_LOW_Msk               0x2UL
#define ISOUART_INTR_WDOG_CNT_TIMEOUT_Pos       2UL
#define ISOUART_INTR_WDOG_CNT_TIMEOUT_Msk       0x4UL
#define ISOUART_INTR_EMM_Pos                    3UL
#define ISOUART_INTR_EMM_Msk                    0x8UL
#define ISOUART_INTR_REQUEST_Pos                4UL
#define ISOUART_INTR_REQUEST_Msk                0x10UL
#define ISOUART_INTR_REQUEST_MATCH_Pos          5UL
#define ISOUART_INTR_REQUEST_MATCH_Msk          0x20UL
#define ISOUART_INTR_BC_WRITE_Pos               6UL
#define ISOUART_INTR_BC_WRITE_Msk               0x40UL
#define ISOUART_INTR_BC_READ_Pos                7UL
#define ISOUART_INTR_BC_READ_Msk                0x80UL
#define ISOUART_INTR_FRAME_ERR_Pos              8UL
#define ISOUART_INTR_FRAME_ERR_Msk              0x100UL
#define ISOUART_INTR_CRC_ERR_Pos                9UL
#define ISOUART_INTR_CRC_ERR_Msk                0x200UL
#define ISOUART_INTR_REG_ACCESS_P_Pos           12UL
#define ISOUART_INTR_REG_ACCESS_P_Msk           0x1000UL
#define ISOUART_INTR_REG_ACCESS_S_Pos           13UL
#define ISOUART_INTR_REG_ACCESS_S_Msk           0x2000UL
#define ISOUART_INTR_UVD_Pos                    14UL
#define ISOUART_INTR_UVD_Msk                    0x4000UL
#define ISOUART_INTR_ECC_ERR_Pos                15UL
#define ISOUART_INTR_ECC_ERR_Msk                0x8000UL
#define ISOUART_INTR_WRITE_COMPLETE_Pos         16UL
#define ISOUART_INTR_WRITE_COMPLETE_Msk         0x10000UL
#define ISOUART_INTR_MASTER_LOW_FRAME_RECEIVED_Pos 17UL
#define ISOUART_INTR_MASTER_LOW_FRAME_RECEIVED_Msk 0x20000UL
#define ISOUART_INTR_MASTER_HIGH_FRAME_RECEIVED_Pos 18UL
#define ISOUART_INTR_MASTER_HIGH_FRAME_RECEIVED_Msk 0x40000UL
#define ISOUART_INTR_MASTER_LOW_SRAM_FULL_Pos   19UL
#define ISOUART_INTR_MASTER_LOW_SRAM_FULL_Msk   0x80000UL
#define ISOUART_INTR_MASTER_HIGH_SRAM_FULL_Pos  20UL
#define ISOUART_INTR_MASTER_HIGH_SRAM_FULL_Msk  0x100000UL
#define ISOUART_INTR_MASTER_INTERNAL_ERROR_Pos  21UL
#define ISOUART_INTR_MASTER_INTERNAL_ERROR_Msk  0x200000UL
#define ISOUART_INTR_MASTER_CRC_ERROR_Pos       22UL
#define ISOUART_INTR_MASTER_CRC_ERROR_Msk       0x400000UL
#define ISOUART_INTR_MASTER_SLAVE_STATUS_ERROR_Pos 23UL
#define ISOUART_INTR_MASTER_SLAVE_STATUS_ERROR_Msk 0x800000UL
#define ISOUART_INTR_MASTER_SLAVE_ACCESS_ERROR_Pos 24UL
#define ISOUART_INTR_MASTER_SLAVE_ACCESS_ERROR_Msk 0x1000000UL
#define ISOUART_INTR_MASTER_SLAVE_ADDRESS_ERROR_Pos 25UL
#define ISOUART_INTR_MASTER_SLAVE_ADDRESS_ERROR_Msk 0x2000000UL
/* ISOUART.INTR_SET */
#define ISOUART_INTR_SET_WAKE_HIGH_Pos          0UL
#define ISOUART_INTR_SET_WAKE_HIGH_Msk          0x1UL
#define ISOUART_INTR_SET_WAKE_LOW_Pos           1UL
#define ISOUART_INTR_SET_WAKE_LOW_Msk           0x2UL
#define ISOUART_INTR_SET_WDOG_CNT_TIMEOUT_Pos   2UL
#define ISOUART_INTR_SET_WDOG_CNT_TIMEOUT_Msk   0x4UL
#define ISOUART_INTR_SET_EMM_Pos                3UL
#define ISOUART_INTR_SET_EMM_Msk                0x8UL
#define ISOUART_INTR_SET_REQUEST_Pos            4UL
#define ISOUART_INTR_SET_REQUEST_Msk            0x10UL
#define ISOUART_INTR_SET_REQUEST_MATCH_Pos      5UL
#define ISOUART_INTR_SET_REQUEST_MATCH_Msk      0x20UL
#define ISOUART_INTR_SET_BC_WRITE_Pos           6UL
#define ISOUART_INTR_SET_BC_WRITE_Msk           0x40UL
#define ISOUART_INTR_SET_BC_READ_Pos            7UL
#define ISOUART_INTR_SET_BC_READ_Msk            0x80UL
#define ISOUART_INTR_SET_FRAME_ERR_Pos          8UL
#define ISOUART_INTR_SET_FRAME_ERR_Msk          0x100UL
#define ISOUART_INTR_SET_CRC_ERR_Pos            9UL
#define ISOUART_INTR_SET_CRC_ERR_Msk            0x200UL
#define ISOUART_INTR_SET_REG_ACCESS_P_Pos       12UL
#define ISOUART_INTR_SET_REG_ACCESS_P_Msk       0x1000UL
#define ISOUART_INTR_SET_REG_ACCESS_S_Pos       13UL
#define ISOUART_INTR_SET_REG_ACCESS_S_Msk       0x2000UL
#define ISOUART_INTR_SET_UVD_Pos                14UL
#define ISOUART_INTR_SET_UVD_Msk                0x4000UL
#define ISOUART_INTR_SET_ECC_ERR_Pos            15UL
#define ISOUART_INTR_SET_ECC_ERR_Msk            0x8000UL
#define ISOUART_INTR_SET_WRITE_COMPLETE_Pos     16UL
#define ISOUART_INTR_SET_WRITE_COMPLETE_Msk     0x10000UL
#define ISOUART_INTR_SET_MASTER_LOW_FRAME_RECEIVED_Pos 17UL
#define ISOUART_INTR_SET_MASTER_LOW_FRAME_RECEIVED_Msk 0x20000UL
#define ISOUART_INTR_SET_MASTER_HIGH_FRAME_RECEIVED_Pos 18UL
#define ISOUART_INTR_SET_MASTER_HIGH_FRAME_RECEIVED_Msk 0x40000UL
#define ISOUART_INTR_SET_MASTER_LOW_SRAM_FULL_Pos 19UL
#define ISOUART_INTR_SET_MASTER_LOW_SRAM_FULL_Msk 0x80000UL
#define ISOUART_INTR_SET_MASTER_HIGH_SRAM_FULL_Pos 20UL
#define ISOUART_INTR_SET_MASTER_HIGH_SRAM_FULL_Msk 0x100000UL
#define ISOUART_INTR_SET_MASTER_INTERNAL_ERROR_Pos 21UL
#define ISOUART_INTR_SET_MASTER_INTERNAL_ERROR_Msk 0x200000UL
#define ISOUART_INTR_SET_MASTER_CRC_ERROR_Pos   22UL
#define ISOUART_INTR_SET_MASTER_CRC_ERROR_Msk   0x400000UL
#define ISOUART_INTR_SET_MASTER_SLAVE_STATUS_ERROR_Pos 23UL
#define ISOUART_INTR_SET_MASTER_SLAVE_STATUS_ERROR_Msk 0x800000UL
#define ISOUART_INTR_SET_MASTER_SLAVE_ACCESS_ERROR_Pos 24UL
#define ISOUART_INTR_SET_MASTER_SLAVE_ACCESS_ERROR_Msk 0x1000000UL
#define ISOUART_INTR_SET_MASTER_SLAVE_ADDRESS_ERROR_Pos 25UL
#define ISOUART_INTR_SET_MASTER_SLAVE_ADDRESS_ERROR_Msk 0x2000000UL
/* ISOUART.INTR_MASK */
#define ISOUART_INTR_MASK_WAKE_HIGH_Pos         0UL
#define ISOUART_INTR_MASK_WAKE_HIGH_Msk         0x1UL
#define ISOUART_INTR_MASK_WAKE_LOW_Pos          1UL
#define ISOUART_INTR_MASK_WAKE_LOW_Msk          0x2UL
#define ISOUART_INTR_MASK_WDOG_CNT_TIMEOUT_Pos  2UL
#define ISOUART_INTR_MASK_WDOG_CNT_TIMEOUT_Msk  0x4UL
#define ISOUART_INTR_MASK_EMM_Pos               3UL
#define ISOUART_INTR_MASK_EMM_Msk               0x8UL
#define ISOUART_INTR_MASK_REQUEST_Pos           4UL
#define ISOUART_INTR_MASK_REQUEST_Msk           0x10UL
#define ISOUART_INTR_MASK_REQUEST_MATCH_Pos     5UL
#define ISOUART_INTR_MASK_REQUEST_MATCH_Msk     0x20UL
#define ISOUART_INTR_MASK_BC_WRITE_Pos          6UL
#define ISOUART_INTR_MASK_BC_WRITE_Msk          0x40UL
#define ISOUART_INTR_MASK_BC_READ_Pos           7UL
#define ISOUART_INTR_MASK_BC_READ_Msk           0x80UL
#define ISOUART_INTR_MASK_FRAME_ERR_Pos         8UL
#define ISOUART_INTR_MASK_FRAME_ERR_Msk         0x100UL
#define ISOUART_INTR_MASK_CRC_ERR_Pos           9UL
#define ISOUART_INTR_MASK_CRC_ERR_Msk           0x200UL
#define ISOUART_INTR_MASK_REG_ACCESS_P_Pos      12UL
#define ISOUART_INTR_MASK_REG_ACCESS_P_Msk      0x1000UL
#define ISOUART_INTR_MASK_REG_ACCESS_S_Pos      13UL
#define ISOUART_INTR_MASK_REG_ACCESS_S_Msk      0x2000UL
#define ISOUART_INTR_MASK_UVD_Pos               14UL
#define ISOUART_INTR_MASK_UVD_Msk               0x4000UL
#define ISOUART_INTR_MASK_ECC_ERR_Pos           15UL
#define ISOUART_INTR_MASK_ECC_ERR_Msk           0x8000UL
#define ISOUART_INTR_MASK_WRITE_COMPLETE_Pos    16UL
#define ISOUART_INTR_MASK_WRITE_COMPLETE_Msk    0x10000UL
#define ISOUART_INTR_MASK_MASTER_LOW_FRAME_RECEIVED_Pos 17UL
#define ISOUART_INTR_MASK_MASTER_LOW_FRAME_RECEIVED_Msk 0x20000UL
#define ISOUART_INTR_MASK_MASTER_HIGH_FRAME_RECEIVED_Pos 18UL
#define ISOUART_INTR_MASK_MASTER_HIGH_FRAME_RECEIVED_Msk 0x40000UL
#define ISOUART_INTR_MASK_MASTER_LOW_SRAM_FULL_Pos 19UL
#define ISOUART_INTR_MASK_MASTER_LOW_SRAM_FULL_Msk 0x80000UL
#define ISOUART_INTR_MASK_MASTER_HIGH_SRAM_FULL_Pos 20UL
#define ISOUART_INTR_MASK_MASTER_HIGH_SRAM_FULL_Msk 0x100000UL
#define ISOUART_INTR_MASK_MASTER_INTERNAL_ERROR_Pos 21UL
#define ISOUART_INTR_MASK_MASTER_INTERNAL_ERROR_Msk 0x200000UL
#define ISOUART_INTR_MASK_MASTER_CRC_ERROR_Pos  22UL
#define ISOUART_INTR_MASK_MASTER_CRC_ERROR_Msk  0x400000UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_STATUS_ERROR_Pos 23UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_STATUS_ERROR_Msk 0x800000UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_ACCESS_ERROR_Pos 24UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_ACCESS_ERROR_Msk 0x1000000UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_ADDRESS_ERROR_Pos 25UL
#define ISOUART_INTR_MASK_MASTER_SLAVE_ADDRESS_ERROR_Msk 0x2000000UL
/* ISOUART.INTR_MASKED */
#define ISOUART_INTR_MASKED_WAKE_HIGH_Pos       0UL
#define ISOUART_INTR_MASKED_WAKE_HIGH_Msk       0x1UL
#define ISOUART_INTR_MASKED_WAKE_LOW_Pos        1UL
#define ISOUART_INTR_MASKED_WAKE_LOW_Msk        0x2UL
#define ISOUART_INTR_MASKED_WDOG_CNT_TIMEOUT_Pos 2UL
#define ISOUART_INTR_MASKED_WDOG_CNT_TIMEOUT_Msk 0x4UL
#define ISOUART_INTR_MASKED_EMM_Pos             3UL
#define ISOUART_INTR_MASKED_EMM_Msk             0x8UL
#define ISOUART_INTR_MASKED_REQUEST_Pos         4UL
#define ISOUART_INTR_MASKED_REQUEST_Msk         0x10UL
#define ISOUART_INTR_MASKED_REQUEST_MATCH_Pos   5UL
#define ISOUART_INTR_MASKED_REQUEST_MATCH_Msk   0x20UL
#define ISOUART_INTR_MASKED_BC_WRITE_Pos        6UL
#define ISOUART_INTR_MASKED_BC_WRITE_Msk        0x40UL
#define ISOUART_INTR_MASKED_BC_READ_Pos         7UL
#define ISOUART_INTR_MASKED_BC_READ_Msk         0x80UL
#define ISOUART_INTR_MASKED_FRAME_ERR_Pos       8UL
#define ISOUART_INTR_MASKED_FRAME_ERR_Msk       0x100UL
#define ISOUART_INTR_MASKED_CRC_ERR_Pos         9UL
#define ISOUART_INTR_MASKED_CRC_ERR_Msk         0x200UL
#define ISOUART_INTR_MASKED_REG_ACCESS_P_Pos    12UL
#define ISOUART_INTR_MASKED_REG_ACCESS_P_Msk    0x1000UL
#define ISOUART_INTR_MASKED_REG_ACCESS_S_Pos    13UL
#define ISOUART_INTR_MASKED_REG_ACCESS_S_Msk    0x2000UL
#define ISOUART_INTR_MASKED_UVD_Pos             14UL
#define ISOUART_INTR_MASKED_UVD_Msk             0x4000UL
#define ISOUART_INTR_MASKED_ECC_ERR_Pos         15UL
#define ISOUART_INTR_MASKED_ECC_ERR_Msk         0x8000UL
#define ISOUART_INTR_MASKED_WRITE_COMPLETE_Pos  16UL
#define ISOUART_INTR_MASKED_WRITE_COMPLETE_Msk  0x10000UL
#define ISOUART_INTR_MASKED_MASTER_LOW_FRAME_RECEIVED_Pos 17UL
#define ISOUART_INTR_MASKED_MASTER_LOW_FRAME_RECEIVED_Msk 0x20000UL
#define ISOUART_INTR_MASKED_MASTER_HIGH_FRAME_RECEIVED_Pos 18UL
#define ISOUART_INTR_MASKED_MASTER_HIGH_FRAME_RECEIVED_Msk 0x40000UL
#define ISOUART_INTR_MASKED_MASTER_LOW_SRAM_FULL_Pos 19UL
#define ISOUART_INTR_MASKED_MASTER_LOW_SRAM_FULL_Msk 0x80000UL
#define ISOUART_INTR_MASKED_MASTER_HIGH_SRAM_FULL_Pos 20UL
#define ISOUART_INTR_MASKED_MASTER_HIGH_SRAM_FULL_Msk 0x100000UL
#define ISOUART_INTR_MASKED_MASTER_INTERNAL_ERROR_Pos 21UL
#define ISOUART_INTR_MASKED_MASTER_INTERNAL_ERROR_Msk 0x200000UL
#define ISOUART_INTR_MASKED_MASTER_CRC_ERROR_Pos 22UL
#define ISOUART_INTR_MASKED_MASTER_CRC_ERROR_Msk 0x400000UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_STATUS_ERROR_Pos 23UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_STATUS_ERROR_Msk 0x800000UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_ACCESS_ERROR_Pos 24UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_ACCESS_ERROR_Msk 0x1000000UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_ADDRESS_ERROR_Pos 25UL
#define ISOUART_INTR_MASKED_MASTER_SLAVE_ADDRESS_ERROR_Msk 0x2000000UL
/* ISOUART.INTR_REG_ACCESS_P */
#define ISOUART_INTR_REG_ACCESS_P_REG_ADDR_Pos  0UL
#define ISOUART_INTR_REG_ACCESS_P_REG_ADDR_Msk  0x7FUL
#define ISOUART_INTR_REG_ACCESS_P_REG_EVENT_Pos 8UL
#define ISOUART_INTR_REG_ACCESS_P_REG_EVENT_Msk 0x300UL
/* ISOUART.INTR_REG_ACCESS_S */
#define ISOUART_INTR_REG_ACCESS_S_REG_ADDR_Pos  0UL
#define ISOUART_INTR_REG_ACCESS_S_REG_ADDR_Msk  0x7FUL
#define ISOUART_INTR_REG_ACCESS_S_REG_EVENT_Pos 8UL
#define ISOUART_INTR_REG_ACCESS_S_REG_EVENT_Msk 0x300UL
/* ISOUART.ECC_CTL */
#define ISOUART_ECC_CTL_ECC_EN_Pos              16UL
#define ISOUART_ECC_CTL_ECC_EN_Msk              0x10000UL
/* ISOUART.ECC_ERR_INJ */
#define ISOUART_ECC_ERR_INJ_ERR_ADDR_Pos        2UL
#define ISOUART_ECC_ERR_INJ_ERR_ADDR_Msk        0xFFFCUL
#define ISOUART_ECC_ERR_INJ_ERR_EN_Pos          20UL
#define ISOUART_ECC_ERR_INJ_ERR_EN_Msk          0x100000UL
#define ISOUART_ECC_ERR_INJ_ERR_PAR_Pos         24UL
#define ISOUART_ECC_ERR_INJ_ERR_PAR_Msk         0x7F000000UL
/* ISOUART.ECC_STATUS */
#define ISOUART_ECC_STATUS_CORR_ERR_Pos         0UL
#define ISOUART_ECC_STATUS_CORR_ERR_Msk         0x1UL
#define ISOUART_ECC_STATUS_NOT_CORR_ERR_Pos     1UL
#define ISOUART_ECC_STATUS_NOT_CORR_ERR_Msk     0x2UL
#define ISOUART_ECC_STATUS_SYNDROME_Pos         8UL
#define ISOUART_ECC_STATUS_SYNDROME_Msk         0x7F00UL
/* ISOUART.DFT_CTL */
#define ISOUART_DFT_CTL_DDFT0_MUX_SEL_Pos       0UL
#define ISOUART_DFT_CTL_DDFT0_MUX_SEL_Msk       0x1FUL
#define ISOUART_DFT_CTL_DDFT1_MUX_SEL_Pos       5UL
#define ISOUART_DFT_CTL_DDFT1_MUX_SEL_Msk       0x3E0UL
#define ISOUART_DFT_CTL_REG_ADFT_SEL_Pos        10UL
#define ISOUART_DFT_CTL_REG_ADFT_SEL_Msk        0x1C00UL
#define ISOUART_DFT_CTL_FRC_REG_EN_Pos          13UL
#define ISOUART_DFT_CTL_FRC_REG_EN_Msk          0x2000UL
#define ISOUART_DFT_CTL_PHY_HS_ADFT_SEL_Pos     14UL
#define ISOUART_DFT_CTL_PHY_HS_ADFT_SEL_Msk     0x1C000UL
#define ISOUART_DFT_CTL_PHY_HS_TRI_TM_Pos       17UL
#define ISOUART_DFT_CTL_PHY_HS_TRI_TM_Msk       0x20000UL
#define ISOUART_DFT_CTL_PHY_LS_ADFT_SEL_Pos     18UL
#define ISOUART_DFT_CTL_PHY_LS_ADFT_SEL_Msk     0x1C0000UL
#define ISOUART_DFT_CTL_PHY_LS_TRI_TM_Pos       21UL
#define ISOUART_DFT_CTL_PHY_LS_TRI_TM_Msk       0x200000UL
#define ISOUART_DFT_CTL_REG_SPARE_Pos           22UL
#define ISOUART_DFT_CTL_REG_SPARE_Msk           0x3FC00000UL
#define ISOUART_DFT_CTL_EN_DFT_LS_Pos           31UL
#define ISOUART_DFT_CTL_EN_DFT_LS_Msk           0x80000000UL
/* ISOUART.DFT_STATUS */
#define ISOUART_DFT_STATUS_DFT_LS_OUT_Pos       0UL
#define ISOUART_DFT_STATUS_DFT_LS_OUT_Msk       0x1UL
/* ISOUART.TRIG_INT_STRUCT */
#define ISOUART_TRIG_INT_STRUCT_TRIG_SRC_Pos    0UL
#define ISOUART_TRIG_INT_STRUCT_TRIG_SRC_Msk    0x3UL
#define ISOUART_TRIG_INT_STRUCT_PRIM_INT_SRC_Pos 2UL
#define ISOUART_TRIG_INT_STRUCT_PRIM_INT_SRC_Msk 0xCUL
#define ISOUART_TRIG_INT_STRUCT_SEC_INT_SRC_Pos 4UL
#define ISOUART_TRIG_INT_STRUCT_SEC_INT_SRC_Msk 0x30UL
/* ISOUART.SRAM_DATA */
#define ISOUART_SRAM_DATA_DATA_E_Pos            0UL
#define ISOUART_SRAM_DATA_DATA_E_Msk            0xFFFFUL
#define ISOUART_SRAM_DATA_DATA_O_Pos            16UL
#define ISOUART_SRAM_DATA_DATA_O_Msk            0xFFFF0000UL
/* ISOUART.SRAM_WITH_ATTR */
#define ISOUART_SRAM_WITH_ATTR_DATA_Pos         0UL
#define ISOUART_SRAM_WITH_ATTR_DATA_Msk         0xFFFFUL
#define ISOUART_SRAM_WITH_ATTR_TRIG_INT_STRUCT_PTR_Pos 16UL
#define ISOUART_SRAM_WITH_ATTR_TRIG_INT_STRUCT_PTR_Msk 0x1F0000UL
#define ISOUART_SRAM_WITH_ATTR_ADDR_INVALID_Pos 21UL
#define ISOUART_SRAM_WITH_ATTR_ADDR_INVALID_Msk 0x200000UL
#define ISOUART_SRAM_WITH_ATTR_ADDR_READONLY_Pos 22UL
#define ISOUART_SRAM_WITH_ATTR_ADDR_READONLY_Msk 0x400000UL
#define ISOUART_SRAM_WITH_ATTR_RESERVED_Pos     23UL
#define ISOUART_SRAM_WITH_ATTR_RESERVED_Msk     0x1800000UL
#define ISOUART_SRAM_WITH_ATTR_IGNORED_Pos      25UL
#define ISOUART_SRAM_WITH_ATTR_IGNORED_Msk      0xFE000000UL
/* ISOUART.PHY_REG_TM */
#define ISOUART_PHY_REG_TM_EN_PHY_HS_TM_Pos     0UL
#define ISOUART_PHY_REG_TM_EN_PHY_HS_TM_Msk     0x1UL
#define ISOUART_PHY_REG_TM_FRC_HS_EN_TR_Pos     2UL
#define ISOUART_PHY_REG_TM_FRC_HS_EN_TR_Msk     0x4UL
#define ISOUART_PHY_REG_TM_FRC_HS_PD_REC_Pos    3UL
#define ISOUART_PHY_REG_TM_FRC_HS_PD_REC_Msk    0x8UL
#define ISOUART_PHY_REG_TM_EN_PHY_LS_TM_Pos     11UL
#define ISOUART_PHY_REG_TM_EN_PHY_LS_TM_Msk     0x800UL
#define ISOUART_PHY_REG_TM_FRC_LS_EN_TR_Pos     13UL
#define ISOUART_PHY_REG_TM_FRC_LS_EN_TR_Msk     0x2000UL
#define ISOUART_PHY_REG_TM_FRC_LS_PD_REC_Pos    14UL
#define ISOUART_PHY_REG_TM_FRC_LS_PD_REC_Msk    0x4000UL
#define ISOUART_PHY_REG_TM_FRC_HS_LS_WAKE_RESET_Pos 15UL
#define ISOUART_PHY_REG_TM_FRC_HS_LS_WAKE_RESET_Msk 0x8000UL
/* ISOUART.TRIM_PHY_V_HS */
#define ISOUART_TRIM_PHY_V_HS_INT_VOLT_Pos      0UL
#define ISOUART_TRIM_PHY_V_HS_INT_VOLT_Msk      0xFFUL
/* ISOUART.TRIM_PHY_V_LS */
#define ISOUART_TRIM_PHY_V_LS_INT_VOLT_Pos      0UL
#define ISOUART_TRIM_PHY_V_LS_INT_VOLT_Msk      0xFFUL
/* ISOUART.TRIM_PHY_ITH_HS */
#define ISOUART_TRIM_PHY_ITH_HS_CURR_Pos        0UL
#define ISOUART_TRIM_PHY_ITH_HS_CURR_Msk        0x7UL
/* ISOUART.TRIM_PHY_ITH_LS */
#define ISOUART_TRIM_PHY_ITH_LS_CURR_Pos        0UL
#define ISOUART_TRIM_PHY_ITH_LS_CURR_Msk        0x7UL


#endif /* _CYIP_ISOUART_H_ */


/* [] END OF FILE */
